// <auto-generated />
using System;
using InventorySystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventorySystem.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260818090833_AddTransactionStatus")]
    partial class AddTransactionStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventorySystem.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Perangkat elektronik dan gadget",
                            Name = "Elektronik"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Perlengkapan alat tulis kantor",
                            Name = "Alat Tulis"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Perabot kantor dan rumah tangga",
                            Name = "Furnitur"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Produk konsumsi makanan dan minuman",
                            Name = "Makanan & Minuman"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pakaian dan aksesoris",
                            Name = "Pakaian"
                        });
                });

            modelBuilder.Entity("InventorySystem.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Laptop 14 inch, RAM 8GB, SSD 512GB",
                            MinimumStock = 5,
                            Name = "Laptop ASUS VivoBook",
                            Price = 8500000m,
                            SKU = "ELK-001",
                            Stock = 25
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mouse wireless ergonomis",
                            MinimumStock = 15,
                            Name = "Mouse Wireless Logitech",
                            Price = 350000m,
                            SKU = "ELK-002",
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Keyboard mechanical RGB",
                            MinimumStock = 10,
                            Name = "Keyboard Mechanical",
                            Price = 750000m,
                            SKU = "ELK-003",
                            Stock = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pulpen gel 0.5mm",
                            MinimumStock = 50,
                            Name = "Pulpen Pilot G2",
                            Price = 15000m,
                            SKU = "ATK-001",
                            Stock = 200
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Buku tulis 100 lembar",
                            MinimumStock = 30,
                            Name = "Buku Tulis A5",
                            Price = 8000m,
                            SKU = "ATK-002",
                            Stock = 150
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kertas HVS 80gsm 500 lembar",
                            MinimumStock = 20,
                            Name = "Kertas HVS A4",
                            Price = 55000m,
                            SKU = "ATK-003",
                            Stock = 8
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Meja kerja kayu 120x60cm",
                            MinimumStock = 3,
                            Name = "Meja Kerja Minimalis",
                            Price = 1200000m,
                            SKU = "FRN-001",
                            Stock = 12
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kursi kantor dengan sandaran mesh",
                            MinimumStock = 5,
                            Name = "Kursi Kantor Ergonomis",
                            Price = 2500000m,
                            SKU = "FRN-002",
                            Stock = 2
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Air mineral kemasan botol",
                            MinimumStock = 100,
                            Name = "Air Mineral 600ml",
                            Price = 4000m,
                            SKU = "MKN-001",
                            Stock = 500
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kopi instan sachet 25g",
                            MinimumStock = 50,
                            Name = "Kopi Sachet Kapal Api",
                            Price = 2500m,
                            SKU = "MKN-002",
                            Stock = 5
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kaos polo cotton combed 30s",
                            MinimumStock = 10,
                            Name = "Kaos Polo Hitam",
                            Price = 125000m,
                            SKU = "PKN-001",
                            Stock = 40
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kemeja katun formal lengan panjang",
                            MinimumStock = 10,
                            Name = "Kemeja Putih Formal",
                            Price = 185000m,
                            SKU = "PKN-002",
                            Stock = 7
                        });
                });

            modelBuilder.Entity("InventorySystem.Models.StockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("StockTransactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Notes = "Stok awal",
                            ProductId = 1,
                            Quantity = 30,
                            Status = 0,
                            TransactionDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Notes = "Penjualan",
                            ProductId = 1,
                            Quantity = 5,
                            Status = 0,
                            TransactionDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Notes = "Restok dari supplier",
                            ProductId = 2,
                            Quantity = 60,
                            Status = 0,
                            TransactionDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Notes = "Penjualan online",
                            ProductId = 2,
                            Quantity = 10,
                            Status = 0,
                            TransactionDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Notes = "Stok awal",
                            ProductId = 3,
                            Quantity = 15,
                            Status = 0,
                            TransactionDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Notes = "Penjualan grosir",
                            ProductId = 3,
                            Quantity = 12,
                            Status = 0,
                            TransactionDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Notes = "Pembelian bulk",
                            ProductId = 4,
                            Quantity = 250,
                            Status = 0,
                            TransactionDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Notes = "Distribusi ke cabang",
                            ProductId = 4,
                            Quantity = 50,
                            Status = 0,
                            TransactionDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Notes = "Pengadaan kantor baru",
                            ProductId = 8,
                            Quantity = 10,
                            Status = 0,
                            TransactionDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            Notes = "Distribusi ke kantor cabang",
                            ProductId = 8,
                            Quantity = 8,
                            Status = 0,
                            TransactionDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Notes = "Stok awal",
                            ProductId = 10,
                            Quantity = 100,
                            Status = 0,
                            TransactionDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            Notes = "Pemakaian harian",
                            ProductId = 10,
                            Quantity = 95,
                            Status = 0,
                            TransactionDate = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1
                        });
                });

            modelBuilder.Entity("InventorySystem.Models.Product", b =>
                {
                    b.HasOne("InventorySystem.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InventorySystem.Models.StockTransaction", b =>
                {
                    b.HasOne("InventorySystem.Models.Product", "Product")
                        .WithMany("StockTransactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InventorySystem.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("InventorySystem.Models.Product", b =>
                {
                    b.Navigation("StockTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
